apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: foundry-password
spec:
  length: 20
  allowRepeat: true
  symbolCharacters: ""
  symbols: 0

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: foundry-password
spec:
  refreshInterval: "87600h"
  target:
    name: foundry-password-secret
    template:
      data:
        FOUNDRY_PASSWORD: "{{ .password }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: "foundry-password"
